services:
  mongo:
    image: mongo:6.0.4
    container_name: mongo_container
    ports:
      - "27018:27017"
    volumes:
      - ./db:/data/db
    networks:
      - mongo-database

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - mongo-database

networks:
  mongo-database:
    driver: bridge
